---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: food2gether
spec:
  selector:
    app: restaurant-service
  type: ClusterIP
  ports:
  - name: restaurant-service
    protocol: TCP
    port: 80
    targetPort: 8080
